# Generated by Django 6.0.3 on 2026-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('participant', 'Participant'), ('organiser', 'Organiser'), ('external', 'External')], default='participant', max_length=20),
        ),
    ]
