# Generated by Django 6.0.3 on 2026-04-20 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookedparticipant',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.booking'),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_events', to='app.booking'),
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cart'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app.event'),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_events', to='app.event'),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.event'),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.event'),
        ),
        migrations.AddField(
            model_name='bookedevent',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_events', to='app.eventslot'),
        ),
        migrations.AddField(
            model_name='organiser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(blank=True, related_name='events', to='app.organiser'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parentevent'),
        ),
        migrations.AddField(
            model_name='participationconstraint',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint', to='app.event'),
        ),
        migrations.AddField(
            model_name='tempbook',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_participants', to='app.cartitem'),
        ),
        migrations.AddField(
            model_name='tempbooktimeslot',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_timeslot', to='app.cartitem'),
        ),
        migrations.AddField(
            model_name='tempbooktimeslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_cart_selections', to='app.eventslot'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='eventslot',
            unique_together={('event', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='tempbooktimeslot',
            unique_together={('cart_item', 'slot')},
        ),
    ]
