# Generated by Django 6.0.3 on 2026-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_image_parentevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedparticipant',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bookedparticipant',
            name='qr_used',
            field=models.BooleanField(default=False),
        ),
    ]
