# Generated by Django 6.0.3 on 2026-04-11 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bookedparticipant_qr_token_bookedparticipant_qr_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedparticipant',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
