# Generated by Django 6.0.3 on 2026-04-17 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bookedparticipant_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedparticipant',
            name='qr_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
