# Generated by Django 6.0.3 on 2026-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookedparticipant_qr_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedparticipant',
            name='qr_generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
